#include "../tools/converter/ConverterEditor.h"
#include "../tools/converter/ConverterSourceMotion.h"
#include "../src/AnimationPack.h"
#include <chrono>
#include <cstring>
#include <fstream>
#include <iostream>
#include <map>
#include <set>

namespace {
using Bytes=std::vector<std::uint8_t>;
std::size_t checks{};
void expect(bool ok,const std::string& message){++checks;if(!ok)throw std::runtime_error(message);}
Bytes read(const std::filesystem::path& path){std::ifstream file(path,std::ios::binary);return Bytes(std::istreambuf_iterator<char>(file),{});}
void write(const std::filesystem::path& path,const Bytes& bytes){std::filesystem::create_directories(path.parent_path());std::ofstream file(path,std::ios::binary);expect(bool(file.write(reinterpret_cast<const char*>(bytes.data()),std::streamsize(bytes.size()))),"write editor fixture");}
template<class T>T word(const Bytes& bytes,std::size_t at){expect(at<=bytes.size()&&sizeof(T)<=bytes.size()-at,"ZIP field bounds");T value;std::memcpy(&value,bytes.data()+at,sizeof value);return value;}
std::map<std::string,Bytes> unzip(const std::filesystem::path& path){
    const auto bytes=read(path);expect(bytes.size()>=22,"ZIP minimum length");const auto end=bytes.size()-22;expect(word<std::uint32_t>(bytes,end)==0x06054b50u,"ZIP end");
    std::size_t at=word<std::uint32_t>(bytes,end+16);std::map<std::string,Bytes> result;expect(word<std::uint16_t>(bytes,end+10)==2,"exactly two override entries");
    for(int entry=0;entry<2;++entry){expect(word<std::uint32_t>(bytes,at)==0x02014b50u&&word<std::uint16_t>(bytes,at+10)==0,"stored ZIP entry");const auto nameSize=word<std::uint16_t>(bytes,at+28),extra=word<std::uint16_t>(bytes,at+30),comment=word<std::uint16_t>(bytes,at+32);const auto size=word<std::uint32_t>(bytes,at+24),local=word<std::uint32_t>(bytes,at+42);expect(at+46+nameSize<=bytes.size(),"ZIP name bounds");std::string name(reinterpret_cast<const char*>(bytes.data()+at+46),nameSize);const auto data=local+30+word<std::uint16_t>(bytes,local+26)+word<std::uint16_t>(bytes,local+28);expect(data+size<=bytes.size(),"ZIP payload bounds");expect(result.emplace(name,Bytes(bytes.begin()+data,bytes.begin()+data+size)).second,"unique ZIP paths");at+=46+nameSize+extra+comment;}expect(at==end,"ZIP directory end");return result;
}
template<class F>void rejects(F function,const std::string& message){bool failed=false;try{function();}catch(const std::exception&){failed=true;}expect(failed,message);}
void same(const fc::Pose& a,const fc::Pose& b,float tolerance,const std::string& label){expect(a.size()==99&&b.size()==99,label+" bones");for(int bone=0;bone<99;++bone){expect((a[bone].t-b[bone].t).length()<=tolerance,label+" translation");expect(fc::angleBetween(a[bone].q,b[bone].q)<=tolerance,label+" rotation");expect((a[bone].s-b[bone].s).length()<=tolerance,label+" scale");}}
int run(const std::filesystem::path& manifest,const std::filesystem::path& output){
    const auto folder=output/("run-"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));std::filesystem::create_directories(folder);
    const auto pack=nlohmann::json::parse(read(manifest));std::map<std::string,std::pair<std::string,std::string>> paths;std::set<std::string> files{"pack.json",pack.at("skeleton").get<std::string>()};
    for(const auto& entry:pack.at("motions")){const auto config=entry.at("config").get<std::string>();const auto metadata=fc::selectAnimationClipConfig(nlohmann::json::parse(read(manifest.parent_path()/config)),entry.at("slot").get<std::string>());const auto hkx=metadata.at("file").get<std::string>();paths[entry.at("slot").get<std::string>()]={hkx,config};files.insert(config);files.insert(hkx);}
    const auto base=folder/"base";for(const auto& file:files)write(base/file,read(manifest.parent_path()/file));const auto input=folder/"input.hkx";write(input,read(base/paths.at("up").first));
    const auto savedInput=read(input),savedManifest=read(base/"pack.json");auto doc=fc::loadConverterBaseEditor(base/"pack.json","up");expect(doc.clip.frames.front().size()==99&&doc.base.parents.size()==99,"canonical editor data");doc.input=input;doc.snapshots.push_back({input,savedInput});
    fc::ConverterEditOptions identity;identity.autoCalibration=false;const auto unchanged=fc::applyConverterEdits(doc,identity);expect(unchanged.clip.duration==doc.clip.duration&&unchanged.clip.frames.size()==doc.clip.frames.size(),"identity timing");
    for(const auto removed:{"sprintCatch","flipUp","flipLeft","flipRight"}){
        rejects([&]{fc::loadConverterEditor(input,base/"pack.json",removed);},"removed slot cannot be imported");rejects([&]{fc::loadConverterBaseEditor(base/"pack.json",removed);},"removed slot cannot be loaded as a base action");
        auto stale=doc;stale.slot=removed;stale.templateConfig["slot"]=removed;rejects([&]{fc::applyConverterEdits(stale,identity);},"stale editor document cannot revive a removed slot");
        auto staleAnimation=unchanged;staleAnimation.config["slot"]=removed;const auto forbidden=folder/(std::string(removed)+"-removed.zip");rejects([&]{fc::exportConverterEditor(stale,staleAnimation,forbidden);},"removed slot cannot be exported from a stale document");expect(!std::filesystem::exists(forbidden),"removed editor slot produces no archive");
    }
    expect(fc::loadConverterBaseEditor(base/"pack.json","backFlipOut").slot=="backFlipOut","wall departure backflip remains editable");
    for(std::size_t frame=0;frame<unchanged.clip.frames.size();++frame)same(unchanged.clip.frames[frame],doc.clip.frames[frame],.00001f,"identity canonical preview");
    auto roundedDoc=doc;roundedDoc.clip.annotations={{roundedDoc.clip.duration+.00003f,0,"animmotion 0 0 0"}};const auto rounded=fc::applyConverterEdits(roundedDoc,identity);expect(rounded.clip.annotations.size()==2&&rounded.clip.annotations.front().time==rounded.clip.duration,"Rounded final motion event is retained at the clip boundary");
    auto synthetic=doc;synthetic.clip.duration=4;synthetic.clip.frames.assign(5,doc.base.rest);synthetic.clip.annotations={{.25f,0,"before"},{1,0,"begin"},{2,0,"middle"},{3,0,"end"},{3.75f,0,"after"},{0,0,std::string(fc::converterSourceMotionMarker)}};
    synthetic.clip.referenceFrame={4,{0,0,1},{0,1,0},{{0,0,0,0},{10,0,0,.1f},{20,0,0,.2f},{30,0,0,.3f},{40,0,0,.4f}}};
    for(int frame=0;frame<5;++frame)synthetic.clip.frames[frame][0].t={10.f*frame,0,0};synthetic.templateConfig["contacts"]={{1,1,1,1},{1,1,1,1}};
    fc::ConverterEditOptions edited;edited.autoCalibration=false;edited.trimIn=1;edited.trimOut=3;edited.speed=2;edited.yawDegrees=90;edited.rootOffset={2,0,0};edited.makeInPlaceAxes={0,1,0};edited.bones={{32,{20,0,0},0,1,.2f}};edited.contacts={{0,0,1,.2f,0}};
    const auto clip=fc::applyConverterEdits(synthetic,edited);expect(clip.clip.duration==1&&clip.clip.frames.size()>=65,"trim and speed resampling represents correction envelopes");expect(clip.clip.annotations.size()==4,"trimmed annotation count includes one retained bake marker");expect(clip.clip.annotations[0].time==0&&clip.clip.annotations[0].text=="begin"&&clip.clip.annotations[1].time==.5f&&clip.clip.annotations[1].text=="middle"&&clip.clip.annotations[2].time==1&&clip.clip.annotations[2].text=="end","annotation retiming");expect(clip.clip.annotations.back().time==0&&clip.clip.annotations.back().text==fc::converterSourceMotionMarker,"trim keeps and repositions bake marker");
    const auto firstWorld=doc.base.world(clip.clip.frames.front()),lastWorld=doc.base.world(clip.clip.frames.back());expect(std::abs(lastWorld[4].t.y-firstWorld[4].t.y)<.0001f,"in-place selected world axis");expect(std::abs(clip.clip.frames.front()[0].t.x-2)<.0001f,"root offset and facing");
    expect(fc::angleBetween(clip.clip.frames.front()[32].q,doc.base.rest[32].q)<.00001f&&fc::angleBetween(clip.clip.frames.back()[32].q,doc.base.rest[32].q)<.00001f,"bone envelope endpoints");expect(std::abs(fc::angleBetween(clip.clip.frames[clip.clip.frames.size()/2][32].q,doc.base.rest[32].q)-20.f*3.14159265358979323846f/180)<.00001f,"bone correction peak");
    expect(fc::sampleConverterContacts(clip,0)[0]==1&&fc::sampleConverterContacts(clip,.5f)[0]==0&&fc::sampleConverterContacts(clip,1)[0]==1,"contact fade and preview");
    expect(clip.clip.referenceFrame.duration==1&&std::abs(clip.clip.referenceFrame.samples.back()[1]-20)<.0001f&&std::abs(clip.clip.referenceFrame.samples.back()[3]-.2f)<.0001f,"extracted metadata trim and facing");
    same(fc::sampleConverterEditor(clip,.5f),clip.clip.frames[clip.clip.frames.size()/2],.00001f,"preview uses export samples");same(fc::sampleConverterEditor(clip,-1),clip.clip.frames.front(),.00001f,"preview clamps before start");same(fc::sampleConverterEditor(clip,3),clip.clip.frames.back(),.00001f,"preview clamps after end");
    const auto archivePath=folder/"edited.zip";const auto report=fc::exportConverterEditor(synthetic,clip,archivePath);expect(report.at("loaded")==fc::activeMotionCount,"edited complete-pack validation");const auto archive=unzip(archivePath);const std::string prefix="meshes/actors/character/animations/FreeClimb/";fc::ConverterInputClip roundTrip;std::string failure;expect(fc::decodeConverterInput(archive.at(prefix+paths.at("up").first),roundTrip,failure),"exported HKX readable");
    expect(roundTrip.duration==clip.clip.duration&&roundTrip.frames.size()==clip.clip.frames.size(),"exported edited timing");for(std::size_t frame=0;frame<roundTrip.frames.size();++frame)same(roundTrip.frames[frame],clip.clip.frames[frame],.00001f,"export equals preview");
    expect(std::count_if(roundTrip.annotations.begin(),roundTrip.annotations.end(),[](const auto& event){return event.text==fc::converterSourceMotionMarker;})==1,"export retains exactly one bake marker");
    auto rawMotion=synthetic;rawMotion.clip.frames.assign(5,doc.base.rest);for(auto& pose:rawMotion.clip.frames)pose[0].t={};rawMotion.clip.referenceFrame={};rawMotion.clip.annotations={{0,0,"animmotion 0 0 0"},{4,0,"animmotion 0 40 80"},{1,0,"start"},{3,0,"finish"}};
    fc::ConverterEditOptions motionEdit;motionEdit.autoCalibration=false;motionEdit.trimIn=1;motionEdit.trimOut=3;motionEdit.speed=2;const auto moved=fc::applyConverterEdits(rawMotion,motionEdit);
    expect((moved.clip.frames.front()[0].t-fc::Vec{0,10,20}).length()<.00001f&&(moved.clip.frames.back()[0].t-fc::Vec{0,30,60}).length()<.00001f,"raw editor motion is baked before trim and speed changes");
    expect(rawMotion.clip.frames.back()[0].t.length()==0&&!fc::converterSourceMotionBaked(rawMotion.clip),"raw editor source remains unchanged");
    expect(std::count_if(moved.clip.annotations.begin(),moved.clip.annotations.end(),[](const auto& event){return event.text==fc::converterSourceMotionMarker&&event.time==0;})==1,"trim preserves a single zero-time marker after all motion keys are outside the interval");
    const auto motionZip=folder/"motion-trimmed.zip";fc::exportConverterEditor(rawMotion,moved,motionZip);const auto motionArchive=unzip(motionZip);fc::ConverterInputClip motionOutput;expect(fc::decodeConverterInput(motionArchive.at(prefix+paths.at("up").first),motionOutput,failure),"trimmed baked motion exports");
    expect(motionOutput.frames.size()==moved.clip.frames.size(),"trimmed baked motion retains preview sampling");for(std::size_t frame=0;frame<motionOutput.frames.size();++frame)same(motionOutput.frames[frame],moved.clip.frames[frame],.00001f,"trimmed baked export matches preview without double application");
    std::vector<std::string> motionWarnings;const auto motionAgainBytes=fc::writeConverterHkx(motionOutput,doc.base,motionWarnings);fc::ConverterInputClip motionAgain;expect(fc::decodeConverterInput(motionAgainBytes,motionAgain,failure),"trimmed motion reimports");expect(motionAgain.annotations.size()==motionOutput.annotations.size(),"trimmed motion reimport does not add another marker");for(std::size_t frame=0;frame<motionAgain.frames.size();++frame)same(motionAgain.frames[frame],motionOutput.frames[frame],.00001f,"trimmed motion reimport preserves all transforms");
    expect(nlohmann::json::parse(archive.at(prefix+paths.at("up").second))==clip.config,"export equals edited contact metadata");expect(read(input)==savedInput&&read(base/"pack.json")==savedManifest,"editor preserves source and base");
    rejects([&]{fc::exportConverterEditor(synthetic,clip,archivePath);},"existing output is protected");expect(read(archivePath).size()>0,"existing output remains intact");
    auto invalid=edited;invalid.trimOut=.5f;rejects([&]{fc::applyConverterEdits(synthetic,invalid);},"reverse trim rejected");invalid=edited;invalid.speed=0;rejects([&]{fc::applyConverterEdits(synthetic,invalid);},"zero speed rejected");
    invalid=edited;invalid.bones={{97,{20,0,0},0,1,.1f}};rejects([&]{fc::applyConverterEdits(synthetic,invalid);},"camera bone correction rejected");invalid=edited;invalid.bones={{32,{45,45,45},0,1,.1f}};rejects([&]{fc::applyConverterEdits(synthetic,invalid);},"combined excessive bone rotation rejected");
    invalid=edited;invalid.contacts={{4,0,1,.1f,1}};rejects([&]{fc::applyConverterEdits(synthetic,invalid);},"unknown contact rejected");invalid=edited;invalid.makeInPlaceAxes.x=.5f;rejects([&]{fc::applyConverterEdits(synthetic,invalid);},"in-place axis is a boolean selection");
    for(unsigned bone:{42u,43u,46u,47u,48u,49u,60u,61u,62u,63u,64u,65u,66u}){expect(!fc::converterEditableBone(doc.base,bone),"runtime-owned attachment is unavailable for correction");invalid=edited;invalid.bones={{bone,{10,0,0},0,1,.1f}};rejects([&]{fc::applyConverterEdits(synthetic,invalid);},"runtime-owned attachment edit rejected");}expect(fc::converterEditableBone(doc.base,32),"body forearm remains editable");
    auto staticDoc=synthetic;staticDoc.clip.frames.assign(2,doc.base.rest);staticDoc.clip.duration=1;staticDoc.clip.annotations.clear();staticDoc.clip.referenceFrame={};fc::ConverterEditOptions staticEdit;staticEdit.autoCalibration=false;staticEdit.bones={{32,{15,0,0},0,1,.2f}};staticEdit.contacts={{0,0,1,.2f,0}};const auto staticEdited=fc::applyConverterEdits(staticDoc,staticEdit);
    expect(staticEdited.clip.frames.size()>=65,"two-frame source gains bounded correction samples");expect(fc::angleBetween(fc::sampleConverterEditor(staticEdited,.5f)[32].q,doc.base.rest[32].q)>.25f,"static source correction is visible at midpoint");expect(fc::sampleConverterContacts(staticEdited,.5f)[0]==0,"static source contact correction is represented");
    const auto staticZip=folder/"static-edited.zip";fc::exportConverterEditor(staticDoc,staticEdited,staticZip);const auto staticArchive=unzip(staticZip);fc::ConverterInputClip staticRoundTrip;expect(fc::decodeConverterInput(staticArchive.at(prefix+paths.at("up").first),staticRoundTrip,failure),"edited static source exports");same(staticRoundTrip.frames[staticRoundTrip.frames.size()/2],staticEdited.clip.frames[staticEdited.clip.frames.size()/2],.00001f,"static correction export equals preview");
    auto mantle=fc::loadConverterEditor(base/paths.at("contextMantle").first,base/"pack.json","contextMantle");fc::ConverterEditOptions special;special.autoCalibration=false;special.windows={{"releaseLeft",.6f,.7f}};const auto mantleEdited=fc::applyConverterEdits(mantle,special);expect(mantleEdited.config["releaseHands"][0][0]==.6f,"special hand marker edits actual runtime field");expect(fc::sampleConverterContacts(mantleEdited,mantleEdited.clip.duration*.8f)[0]==0,"mantle preview derives actual hand support");
    special.contacts={{0,0,1,.1f,1}};rejects([&]{fc::applyConverterEdits(mantle,special);},"generic contact edit cannot pretend to change special action");special.contacts.clear();special.windows={{"replantSample",.8f,.8f}};rejects([&]{fc::applyConverterEdits(mantle,special);},"inconsistent mantle calibration rejected");
    auto side=fc::loadConverterEditor(base/paths.at("contextHopLeft").first,base/"pack.json","contextHopLeft");special.windows={{"vertical",0,.1f}};rejects([&]{fc::applyConverterEdits(side,special);},"vertical phase cannot overlap loaded source hands");
    special.windows.clear();fc::ConverterGeometryEdit sideGeometry;sideGeometry.stride=side.templateConfig.at("stride").get<float>();sideGeometry.height=side.templateConfig.at("height").get<float>();const auto& travel=side.templateConfig.at("travel");sideGeometry.travel={travel[0].get<float>(),travel[1].get<float>(),travel[2].get<float>()};sideGeometry.path=side.templateConfig.at("path").get<std::vector<std::array<float,4>>>();sideGeometry.path[1][2]+=1;special.geometry=sideGeometry;
    const auto sideEdited=fc::applyConverterEdits(side,special);expect(sideEdited.config.at("path")[1][2]==sideGeometry.path[1][2],"bounded movement path edit changes actual runtime metadata");fc::exportConverterEditor(side,sideEdited,folder/"path.zip");special.geometry->travel.x=10;rejects([&]{fc::applyConverterEdits(side,special);},"side travel cannot point at the wrong endpoint");special.geometry=sideGeometry;special.geometry->path.back()[2]=1;rejects([&]{fc::applyConverterEdits(side,special);},"movement path end must remain anchored");
    auto geometry=identity;geometry.geometry=fc::ConverterGeometryEdit{123,4,{0,0,4},{}};const auto geometryEdited=fc::applyConverterEdits(doc,geometry);expect(geometryEdited.config.at("stride")==123&&geometryEdited.config.at("height")==4,"ordinary stride and height edit");geometry.geometry->stride=501;rejects([&]{fc::applyConverterEdits(doc,geometry);},"movement scalar bounds retained");
    fc::ConverterEditOptions automatic;const auto calibrated=fc::applyConverterEdits(doc,automatic);expect(calibrated.confidence>=0&&calibrated.confidence<=1&&!calibrated.phaseMap.empty(),"automatic calibration exposes confidence and phase mapping");expect(calibrated.config.at("file")==doc.templateConfig.at("file")&&calibrated.config.at("slot")=="up","automatic calibration preserves slot identity");fc::exportConverterEditor(doc,calibrated,folder/"automatic.zip");
    auto down=fc::loadConverterBaseEditor(base/"pack.json","down");
    for(const float target:{0.f,1.f}){fc::ConverterEditOptions bounded;bounded.contacts={{0,0,1,.01f+(.3f-.01f)*.138f,target}};const auto output=fc::applyConverterEdits(down,bounded);
        for(const auto& row:output.config.at("contacts"))for(const auto& value:row){const float weight=value.get<float>();expect(std::isfinite(weight)&&weight>=0&&weight<=1,"contact edit interpolation remains bounded");}
        for(std::size_t frame=0;frame<output.clip.frames.size();++frame)for(const auto weight:fc::sampleConverterContacts(output,output.clip.duration*float(frame)/float(output.clip.frames.size()-1)))expect(weight>=0&&weight<=1,"edited timeline samples remain bounded");
        fc::exportConverterEditor(down,output,folder/(target==0?"down-release.zip":"down-support.zip"));
    }
    for(const bool automatic:{false,true})for(const float weight:{-.0000001f,1.0000007f}){auto invalidContacts=down;invalidContacts.templateConfig["contacts"][0][0]=weight;fc::ConverterEditOptions bounded;bounded.autoCalibration=automatic;bounded.contacts={{0,0,1,.05f,1}};rejects([&]{fc::applyConverterEdits(invalidContacts,bounded);},"out-of-range source weights are rejected rather than repaired");}
    auto changed=read(input);changed.back()^=1;write(input,changed);const auto rejectedOutput=folder/"changed.zip";rejects([&]{fc::exportConverterEditor(doc,calibrated,rejectedOutput);},"changed input invalidates editor session");expect(!std::filesystem::exists(rejectedOutput),"changed input publishes nothing");write(input,savedInput);
    changed=read(base/paths.at("up").second);changed.push_back(' ');const auto originalMetadata=read(base/paths.at("up").second);write(base/paths.at("up").second,changed);rejects([&]{fc::exportConverterEditor(doc,calibrated,rejectedOutput);},"changed base invalidates editor session");expect(!std::filesystem::exists(rejectedOutput),"changed base publishes nothing");write(base/paths.at("up").second,originalMetadata);
    auto shared=nlohmann::json::parse(originalMetadata);shared["file"]=paths.at("down").first;const auto sharedText=shared.dump(2);write(base/paths.at("up").second,Bytes(sharedText.begin(),sharedText.end()));const auto sharedDoc=fc::loadConverterBaseEditor(base/"pack.json","up");expect(sharedDoc.input==std::filesystem::weakly_canonical(base/paths.at("down").first),"base loader resolves the configured shared file rather than assuming slot.hkx");write(base/paths.at("up").second,originalMetadata);
    std::cout<<"pass: "<<checks<<" editor assertions; output="<<folder.string()<<'\n';return 0;
}
}
#ifdef _WIN32
int wmain(int argc,wchar_t** argv){try{if(argc!=3)throw std::runtime_error("Need pack.json output-directory");return run(argv[1],argv[2]);}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
#else
int main(int argc,char** argv){try{if(argc!=3)throw std::runtime_error("Need pack.json output-directory");return run(argv[1],argv[2]);}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
#endif
