#include "../tools/converter/ConverterActionAuthoring.h"
#include "../tools/converter/ConverterTimeline.h"
#include "../tools/converter/ConverterSourceMotion.h"
#include "../tools/converter/ConverterWallRunGroup.h"
#include "../src/AnimationPack.h"
#include <chrono>
#include <cstring>
#include <fstream>
#include <iostream>
#include <map>

namespace {
using Bytes=std::vector<std::uint8_t>;
std::size_t checks{};
void expect(bool condition,const std::string& message){++checks;if(!condition)throw std::runtime_error(message);}
Bytes read(const std::filesystem::path& path){std::ifstream file(path,std::ios::binary);return Bytes(std::istreambuf_iterator<char>(file),{});}
void write(const std::filesystem::path& path,const Bytes& bytes){std::filesystem::create_directories(path.parent_path());std::ofstream file(path,std::ios::binary);expect(bool(file.write(reinterpret_cast<const char*>(bytes.data()),std::streamsize(bytes.size()))),"Write fixture");}
void json(const std::filesystem::path& path,const nlohmann::json& value){const auto text=value.dump(2)+"\n";write(path,Bytes(text.begin(),text.end()));}
void pose(const fc::Pose& a,const fc::Pose& b,const std::string& context){expect(a.size()==99&&b.size()==99,context+" bone count");for(int bone=0;bone<99;++bone){expect((a[bone].t-b[bone].t).length()<.0001f,context+" translation");expect((a[bone].s-b[bone].s).length()<.00001f,context+" scale");expect(fc::angleBetween(a[bone].q,b[bone].q)<.0001f,context+" rotation");}}
template<class F>void rejects(F&& function,const char* message){bool rejected=false;try{function();}catch(const std::exception&){rejected=true;}expect(rejected,message);}
template<class T>T word(const Bytes& data,std::size_t offset){expect(offset<=data.size()&&sizeof(T)<=data.size()-offset,"ZIP field bounds");T value;std::memcpy(&value,data.data()+offset,sizeof(T));return value;}
std::map<std::string,Bytes> unzip(const std::filesystem::path& path){
    const auto bytes=read(path);expect(bytes.size()>=22,"ZIP minimum length");const auto end=bytes.size()-22;expect(word<std::uint32_t>(bytes,end)==0x06054b50u,"ZIP end");const auto count=word<std::uint16_t>(bytes,end+10);expect(count==2,"Group export has one HKX and one JSON");
    std::size_t at=word<std::uint32_t>(bytes,end+16);std::map<std::string,Bytes> result;for(unsigned i=0;i<count;++i){expect(word<std::uint32_t>(bytes,at)==0x02014b50u&&word<std::uint16_t>(bytes,at+10)==0,"Stored ZIP entry");const auto size=word<std::uint32_t>(bytes,at+24),local=word<std::uint32_t>(bytes,at+42);const auto n=word<std::uint16_t>(bytes,at+28),x=word<std::uint16_t>(bytes,at+30),c=word<std::uint16_t>(bytes,at+32);expect(at+46+n<=bytes.size(),"ZIP name bounds");const auto data=local+30+word<std::uint16_t>(bytes,local+26)+word<std::uint16_t>(bytes,local+28);expect(data+size<=bytes.size(),"ZIP payload bounds");result.emplace(std::string(reinterpret_cast<const char*>(bytes.data()+at+46),n),Bytes(bytes.begin()+data,bytes.begin()+data+size));at+=46+n+x+c;}return result;
}
void sourceReload(const std::filesystem::path& base,const std::filesystem::path& folder){
    auto document=std::make_unique<fc::ConverterWallRunDocument>(fc::loadConverterWallRunEditor(base/"pack.json","runRight"));
    expect(document->document.authored,"Reloaded external complete action retains source preview identity");
    expect(!document->document.templateConfig.contains("authoredPlayback")&&!document->document.templateConfig.contains("frameRange")&&!document->document.templateConfig.contains("rootShift"),"Whole document does not reuse loop-only metadata");
    expect((document->document.clip.frames.back()[0].t-document->document.clip.frames.front()[0].t-fc::Vec{0,80,0}).length()<.0001f,"Complete reloaded source retains its baked Root displacement");
    for(std::size_t frame=0;frame<document->document.clip.frames.size();++frame)expect((document->document.clip.frames[frame][0].t-fc::Vec{2,80*float(frame)/float(document->document.clip.frames.size()-1),0}).length()<.0001f,"Reloaded complete Root matches the original 80-unit source and explicit two-unit offset");
    std::string failure;auto unchanged=std::make_unique<fc::ConverterWallRunSequence>();expect(fc::applyConverterWallRunEdits(*document,{},document->cuts,*unchanged,failure),"Reloaded source no-op: "+failure);
    for(std::size_t frame=0;frame<unchanged->whole.clip.frames.size();++frame)pose(unchanged->whole.clip.frames[frame],document->document.clip.frames[frame],"Reloaded no-op whole fidelity");
    for(unsigned stage=0;stage<3;++stage){expect(unchanged->stages[stage].document.authored&&unchanged->stages[stage].animation.config==document->stages[stage].animation.config,"Reloaded no-op retains authored stage metadata");for(std::size_t frame=0;frame<unchanged->stages[stage].animation.clip.frames.size();++frame)pose(unchanged->stages[stage].animation.clip.frames[frame],document->stages[stage].animation.clip.frames[frame],"Reloaded no-op stage fidelity");}
    fc::ConverterEditOptions edits;edits.speed=1.5f;edits.yawDegrees=30;edits.rootOffset={1,2,3};const auto facing=fc::Quat::axis({0,0,1},3.14159265358979323846f/6);
    auto changed=std::make_unique<fc::ConverterWallRunSequence>();expect(fc::applyConverterWallRunEdits(*document,edits,document->cuts,*changed,failure),"Reloaded complete source edit: "+failure);
    expect(changed->whole.clip.frames.size()==document->document.clip.frames.size()&&std::abs(changed->whole.clip.duration-document->document.clip.duration/edits.speed)<.00001f,"Editing source preserves the complete frame grid and requested clock");
    for(std::size_t frame=0;frame<changed->whole.clip.frames.size();++frame)expect((changed->whole.clip.frames[frame][0].t-facing.rotate(document->document.clip.frames[frame][0].t)-edits.rootOffset).length()<.0001f,"Whole edit retains Root movement and existing positional correction");
    for(unsigned stage=0;stage<3;++stage){const auto& before=document->stages[stage].animation.clip;const auto& after=changed->stages[stage];expect(after.document.authored&&after.animation.config.at("version")==2&&after.animation.config.at("authoredPlayback").contains("trajectory"),"Edited source roles retain independent source trajectories");expect(after.animation.clip.frames.size()==before.frames.size(),"Editing source roles retains every source key");for(std::size_t frame=0;frame<before.frames.size();++frame)expect((after.animation.clip.frames[frame][0].t-facing.rotate(before.frames[frame][0].t)-edits.rootOffset).length()<.0001f,"Stage edit retains source Root movement without adding or removing origin offsets");}
    for(unsigned stage=0;stage<3;++stage)for(std::size_t frame=0;frame<changed->stages[stage].animation.clip.frames.size();++frame)expect((changed->stages[stage].animation.clip.frames[frame][0].t+facing.rotate(document->rootShifts[stage])-changed->whole.clip.frames[document->ranges[stage][0]+frame][0].t).length()<.0001f,"Edited local-stage Root plus its rotated shift reproduces the full timeline Root");
    auto install=[&](const fc::ConverterWallRunSequence& sequence,const std::string& filename){std::vector<fc::ConverterEditorExport> entries;for(const auto& stage:sequence.stages)entries.push_back({&stage.document,&stage.animation,sequence.primary});const auto archive=folder/filename;expect(fc::exportConverterEditorGroup(entries,archive).at("loaded")==fc::activeMotionCount,"Reloaded complete source validates through the runtime loader");const std::string prefix="meshes/actors/character/animations/FreeClimb/";for(const auto& [name,bytes]:unzip(archive)){expect(name.starts_with(prefix),"Reloaded override remains inside animation namespace");write(base/name.substr(prefix.size()),bytes);}};
    install(*changed,"edited-reloaded-direction.zip");auto again=std::make_unique<fc::ConverterWallRunDocument>(fc::loadConverterWallRunEditor(base/"pack.json","runRight"));expect(again->document.authored&&again->document.clip.frames.size()==changed->whole.clip.frames.size(),"Edited source pack reopens as a complete authored action");for(std::size_t frame=0;frame<again->document.clip.frames.size();++frame)pose(again->document.clip.frames[frame],changed->whole.clip.frames[frame],"Edited complete Root and pose round trip");
    const auto manifest=nlohmann::json::parse(read(base/"pack.json"));const auto entry=std::find_if(manifest.at("motions").begin(),manifest.at("motions").end(),[](const auto& value){return value.at("slot")=="runRight";});expect(entry!=manifest.at("motions").end(),"Mixed fixture has the selected direction");const auto metadataPath=base/entry->at("config").get<std::string>();auto metadata=nlohmann::json::parse(read(metadataPath));auto& launch=fc::selectAnimationClipConfig(metadata,"runLaunchRight","runRight");launch.erase("authoredPlayback");launch["version"]=1;json(metadataPath,metadata);fc::Library mixedLibrary;expect(fc::loadAnimationPack(mixedLibrary,base/"pack.json").committed,"Mixed fixture is accepted by the real runtime loader");
    auto mixedDocument=std::make_unique<fc::ConverterWallRunDocument>(fc::loadConverterWallRunEditor(base/"pack.json","runRight"));auto mixed=std::make_unique<fc::ConverterWallRunSequence>();expect(fc::applyConverterWallRunEdits(*mixedDocument,{},mixedDocument->cuts,*mixed,failure),"Mixed fixture no-op");install(*mixed,"mixed-direction.zip");
    auto reloadedMixed=std::make_unique<fc::ConverterWallRunDocument>(fc::loadConverterWallRunEditor(base/"pack.json","runRight"));expect(reloadedMixed->document.authored,"Mixed complete action with any source stage retains source preview");for(unsigned stage=0;stage<3;++stage)expect(reloadedMixed->stages[stage].document.authored==(stage!=0),"Mixed stage identities survive reload");
    auto mixedNoop=std::make_unique<fc::ConverterWallRunSequence>();expect(fc::applyConverterWallRunEdits(*reloadedMixed,{},reloadedMixed->cuts,*mixedNoop,failure),"Mixed complete no-op");for(unsigned stage=0;stage<3;++stage)expect(mixedNoop->stages[stage].animation.config==reloadedMixed->stages[stage].animation.config,"Mixed no-op preserves both calibrated and source metadata");
    fc::ConverterEditOptions speed;speed.speed=1.25f;auto mixedEdit=std::make_unique<fc::ConverterWallRunSequence>();expect(fc::applyConverterWallRunEdits(*reloadedMixed,speed,reloadedMixed->cuts,*mixedEdit,failure),"Mixed complete speed edit: "+failure);for(unsigned stage=0;stage<3;++stage){const auto& before=reloadedMixed->stages[stage].animation;const auto& after=mixedEdit->stages[stage];expect(after.document.authored==(stage!=0)&&after.animation.config.contains("authoredPlayback")==bool(stage),"Mixed edits preserve each stage's playback mode");expect(after.animation.clip.frames.size()==before.clip.frames.size(),"Mixed edit retains source keys");for(std::size_t frame=0;frame<before.clip.frames.size();++frame)pose(after.animation.clip.frames[frame],before.clip.frames[frame],"Mixed speed edit retains calibrated and source Root");}
}
int run(const std::filesystem::path& manifest,const std::filesystem::path& output){
    const auto folder=output/("run-"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));const auto base=folder/"base";std::filesystem::create_directories(base);
    const auto initial=fc::loadConverterBaseEditor(manifest,"runUp");for(const auto& snapshot:initial.snapshots){const auto relative=snapshot.path.lexically_relative(initial.pack.parent_path());expect(!relative.empty()&&*relative.begin()!="..","Base snapshot containment");write(base/relative,snapshot.bytes);}
    std::vector<fc::ConverterPreparedClip> stages;std::map<std::string,fc::ConverterInputClip> originals;
    for(const auto direction:{"runUp","runLeft","runRight","runDiagonalLeft","runDiagonalRight"}){const auto roles=fc::converter::wallRunStages(direction);for(std::size_t stage=0;stage<3;++stage){const auto doc=fc::loadConverterBaseEditor(base/"pack.json",std::string(roles[stage]),direction);originals.emplace(std::string(direction)+"/"+doc.slot,doc.clip);stages.push_back({doc.clip,doc.templateConfig,{},doc.snapshots,direction});}}
    const auto brace=fc::loadConverterBaseEditor(base/"pack.json","sideBrace");stages.push_back({brace.clip,brace.templateConfig,{},brace.snapshots,{}});
    std::vector<fc::ConverterTimelinePart> changedSpeed;for(unsigned i=3;i<6;++i)changedSpeed.push_back({stages[i].config.at("slot").get<std::string>(),stages[i].clip});
    changedSpeed.back().clip.duration/=1.251f;for(auto& event:changedSpeed.back().clip.annotations)event.time/=1.251f;
    const auto aligned=fc::composeConverterTimeline(changedSpeed);expect(std::any_of(aligned.warnings.begin(),aligned.warnings.end(),[](const auto& text){return text.find("preserving every source key")!=std::string::npos;}),"Ordinary fractional speed keeps source keys on a bounded common timeline");
    for(std::size_t stage=0;stage<3;++stage){const auto& range=aligned.ranges[stage];const auto intervals=range.frames[1]-range.frames[0],originalIntervals=changedSpeed[stage].clip.frames.size()-1;expect(intervals%originalIntervals==0,"Speed alignment preserves every source key");for(std::size_t frame=0;frame<=originalIntervals;++frame){auto actual=aligned.clip.frames[range.frames[0]+frame*(intervals/originalIntervals)];actual[0].t=actual[0].t-range.rootShift;pose(actual,changedSpeed[stage].clip.frames[frame],"Fractional speed key fidelity");}}
    auto composed=fc::composeConverterWallRunPack(initial.base,stages);expect(composed.config.at("version")==2&&composed.config.at("clips").size()==10&&composed.config.at("sequences").size()==5,"Five complete directions retain ten runtime identities");
    for(auto& clip:composed.config["clips"])clip["file"]="wallRun.hkx";for(auto& sequence:composed.config["sequences"])for(const auto key:{"launch","catch"})sequence[key]["file"]="wallRun.hkx";
    fc::ConverterInputClip ambiguous;std::string failure;expect(!fc::decodeConverterInput(composed.hkx,ambiguous,failure)&&failure.find("multiple")!=std::string::npos,"Multiple timelines never silently pick the first animation");
    for(const auto direction:{"runUp","runLeft","runRight","runDiagonalLeft","runDiagonalRight"}){
        fc::ConverterInputClip timeline;expect(fc::decodeConverterInput(composed.hkx,timeline,failure,direction),"Read complete direction");expect(timeline.duration>.9f,"Default direction includes its start and ending");
        const auto roles=fc::converter::wallRunStages(direction);for(std::size_t stage=0;stage<3;++stage){const auto& cfg=fc::selectAnimationClipConfig(composed.config,roles[stage],direction);const auto sliced=fc::sliceConverterTimeline(timeline,cfg);const auto& original=originals.at(std::string(direction)+"/"+std::string(roles[stage]));expect(sliced.frames.size()==original.frames.size()&&std::abs(sliced.duration-original.duration)<.000001f,"Default stage clock survives timeline migration");for(std::size_t frame=0;frame<sliced.frames.size();++frame)pose(sliced.frames[frame],original.frames[frame],"Default stage preserved");}
    }
    write(base/"wallRun.hkx",composed.hkx);json(base/"configs"/"wallRun.json",composed.config);auto groupManifest=nlohmann::json::parse(read(base/"pack.json"));for(auto& entry:groupManifest["motions"])if(fc::converter::actionPrimaryForSlot(entry.at("slot").get<std::string>())=="wallRun")entry["config"]="configs/wallRun.json";json(base/"pack.json",groupManifest);fc::Library migrated;const auto ready=fc::loadAnimationPack(migrated,base/"pack.json");expect(ready.committed&&ready.loaded==fc::activeMotionCount,"Migrated full pack loads transactionally");
    for(const auto& completePack:{manifest,base/"pack.json"})for(const auto direction:{"runUp","runLeft","runRight","runDiagonalLeft","runDiagonalRight"}){
        const auto document=fc::loadConverterWallRunEditor(completePack,direction);expect(document.stages.size()==(std::string_view(direction)=="runUp"?3:4)&&document.document.slot==direction,"Whole editor loads one complete direction");
        expect(document.document.clip.duration>document.stages[1].animation.clip.duration&&document.cuts.loopBegin>0&&document.cuts.loopEnd<document.document.clip.duration,"Whole editor keeps start, loop and ending on one timeline");
        fc::ConverterWallRunSequence unchanged;expect(fc::applyConverterWallRunEdits(document,{},document.cuts,unchanged,failure),"Whole default no-op succeeds: "+failure);
        expect(unchanged.whole.clip.frames.size()==document.document.clip.frames.size(),"No-op full preview keeps original frame count");
        for(std::size_t frame=0;frame<unchanged.whole.clip.frames.size();++frame)for(unsigned bone=0;bone<99;++bone)expect(std::memcmp(&unchanged.whole.clip.frames[frame][bone],&document.document.clip.frames[frame][bone],sizeof(fc::Transform))==0,"No-op complete timeline keeps exact transforms");
        for(unsigned stage=0;stage<3;++stage){expect(unchanged.stages[stage].animation.config==document.stages[stage].animation.config,"No-op keeps complete calibrated stage metadata");expect(!unchanged.stages[stage].document.authored&&!unchanged.stages[stage].animation.config.contains("authoredPlayback"),"No-op defaults do not become source playback");for(std::size_t frame=0;frame<unchanged.stages[stage].animation.clip.frames.size();++frame)for(unsigned bone=0;bone<99;++bone)expect(std::memcmp(&unchanged.stages[stage].animation.clip.frames[frame][bone],&document.stages[stage].animation.clip.frames[frame][bone],sizeof(fc::Transform))==0,"No-op stages preserve exact source transforms");}
        fc::ConverterEditOptions speed;speed.speed=1.5f;fc::ConverterWallRunSequence sped;expect(fc::applyConverterWallRunEdits(document,speed,document.cuts,sped,failure),"Whole speed applies: "+failure);expect(std::abs(sped.whole.clip.duration-document.document.clip.duration/1.5f)<.000001f,"Whole speed changes the full timeline");
        for(unsigned stage=0;stage<3;++stage){expect(std::abs(sped.stages[stage].animation.clip.duration-document.stages[stage].animation.clip.duration/1.5f)<.000001f,"Whole speed reaches every timing stage");expect(sped.stages[stage].animation.config.at("version")==1&&!sped.stages[stage].animation.config.contains("authoredPlayback"),"Editing default speed preserves legacy playback calibration");}
        fc::ConverterEditOptions contacts;contacts.contacts={{0,0,1,0,.75f}};fc::ConverterWallRunSequence supported;expect(fc::applyConverterWallRunEdits(document,contacts,document.cuts,supported,failure),"Whole contacts apply: "+failure);for(unsigned stage=0;stage<3;++stage)expect(std::abs(fc::sampleConverterContacts(supported.stages[stage].animation,supported.stages[stage].animation.clip.duration*.5f)[0]-.75f)<.00001f,"One contact correction spans every stage");
        fc::ConverterEditOptions poseEdit;poseEdit.bones={{32,{8,0,0},0,1,0}};fc::ConverterWallRunSequence corrected;expect(fc::applyConverterWallRunEdits(document,poseEdit,document.cuts,corrected,failure),"Whole local correction applies: "+failure);for(unsigned stage=0;stage<3;++stage)expect(fc::angleBetween(corrected.stages[stage].animation.clip.frames.front()[32].q,document.stages[stage].animation.clip.frames.front()[32].q)>.1f,"Whole local correction reaches every stage");
        fc::ConverterEditOptions crop;crop.trimIn=document.cuts.loopBegin+.001f;fc::ConverterWallRunSequence invalid;expect(!fc::applyConverterWallRunEdits(document,crop,document.cuts,invalid,failure)&&invalid.stages.empty(),"Cropping past the loop boundary fails without partial output");
    }
    auto source=fc::loadConverterBaseEditor(base/"pack.json","runUp");auto raw=source.clip;raw.duration=4;raw.frames.assign(121,source.base.rest);raw.rotations.clear();raw.referenceFrame={};raw.annotations={{0,0,"animmotion 0 0 0"},{4,0,"animmotion 0 80 0"},{.8f,0,"LoopStart"},{3.2f,0,"LoopEnd"},{3.9f,0,"Ending"}};
    for(std::size_t frame=0;frame<raw.frames.size();++frame)raw.frames[frame][32].q=(raw.frames[frame][32].q*fc::Quat::axis({1,0,0},.1f*std::sin(float(frame)*.07f))).unit();
    const auto input=folder/"complete-source.hkx";std::vector<std::string> warnings;write(input,fc::writeConverterHkx(raw,source.base,warnings));const auto savedInput=read(input);source=fc::loadConverterEditor(input,base/"pack.json","runUp","runUp");
    fc::ConverterEditOptions edits;edits.autoCalibration=false;edits.rootOffset={2,0,0};edits.contacts={{0,.1f,.9f,.1f,.8f}};edits.bones={{32,{5,0,0},.1f,.9f,.1f}};
    fc::ConverterWallRunSequence sequence;expect(fc::authorWallRunSequence(source,edits,"runRight",{.8f,3.2f},sequence,failure),"Author complete source: "+failure);expect(sequence.stages.size()==3&&sequence.primary=="runRight","Complete source emits one direction's three timing roles");
    const auto whole=fc::applyConverterEdits(source,edits);const auto frameInterval=whole.clip.duration/float(whole.clip.frames.size()-1);std::vector<fc::ConverterTimelinePart> parts;
    for(const auto& stage:sequence.stages){expect(stage.document.direction=="runRight"&&stage.animation.config.at("version")==2,"Each timing role has the selected direction and source playback");parts.push_back({stage.document.slot,stage.animation.clip});const auto again=fc::applyConverterEdits(stage.document,stage.options);expect(again.clip.frames.size()==stage.animation.clip.frames.size(),"Returning to a generated role retains frames");for(std::size_t frame=0;frame<again.clip.frames.size();++frame)pose(again.clip.frames[frame],stage.animation.clip.frames[frame],"Returning to generated role preserves edits");expect(again.config.at("contacts")==stage.animation.config.at("contacts"),"Returning to generated role preserves source Contacts");}
    const auto joined=fc::composeConverterTimeline(parts);expect(std::abs(joined.clip.duration-whole.clip.duration)<.00001f&&joined.clip.frames.size()==whole.clip.frames.size(),"A continuous source gains no hold frames or fake transitions");for(std::size_t frame=0;frame<joined.clip.frames.size();++frame)pose(joined.clip.frames[frame],whole.clip.frames[frame],"Whole-source timeline preserves every edited pose");
    expect(std::count_if(joined.clip.annotations.begin(),joined.clip.annotations.end(),[](const auto& event){return event.text==fc::converterSourceMotionMarker;})==1,"Combined source has one bake marker");
    auto irregular=parts;irregular.front().clip.duration*=1.013f;const auto resampled=fc::composeConverterTimeline(irregular);expect(resampled.clip.frames.size()<=1201&&std::any_of(resampled.warnings.begin(),resampled.warnings.end(),[](const auto& text){return text.find("resampled")!=std::string::npos;}),"Unmatched stage rates receive bounded, reported resampling");
    for(std::size_t stage=0;stage<irregular.size();++stage){const auto& range=resampled.ranges[stage];const auto& shift=range.rootShift;const auto output=fc::sliceConverterTimeline(resampled.clip,{{"frameRange",range.frames},{"rootShift",{shift.x,shift.y,shift.z}}});expect(std::abs(output.duration-irregular[stage].clip.duration)<=resampled.clip.duration/float(resampled.clip.frames.size()-1)*.501f,"Resampled section clock changes by at most half one sample interval");}
    for(const auto name:{"LoopStart","LoopEnd","Ending"}){const auto event=std::find_if(joined.clip.annotations.begin(),joined.clip.annotations.end(),[&](const auto& value){return value.text==name;});expect(event!=joined.clip.annotations.end(),"Source event retained");const auto original=std::find_if(whole.clip.annotations.begin(),whole.clip.annotations.end(),[&](const auto& value){return value.text==name;});expect(std::abs(event->time-original->time)<frameInterval*.001f,"Source event keeps its time");}
    std::vector<fc::ConverterEditorExport> exportStages;for(const auto& stage:sequence.stages)exportStages.push_back({&stage.document,&stage.animation,sequence.primary});const auto exported=folder/"direction.zip";const auto report=fc::exportConverterEditorGroup(exportStages,exported);expect(report.at("loaded")==fc::activeMotionCount,"Direction export validates complete pack");
    const auto archive=unzip(exported);const std::string prefix="meshes/actors/character/animations/FreeClimb/";for(const auto& [name,bytes]:archive){expect(name.starts_with(prefix),"Override uses animation namespace");write(base/name.substr(prefix.size()),bytes);}
    fc::Library editedLibrary;expect(fc::loadAnimationPack(editedLibrary,base/"pack.json").committed,"Exported timelines are accepted by runtime loader");
    for(const auto direction:{"runUp","runLeft","runDiagonalLeft","runDiagonalRight"}){const auto roles=fc::converter::wallRunStages(direction);for(std::size_t i=0;i<3;++i){const auto doc=fc::loadConverterBaseEditor(base/"pack.json",std::string(roles[i]),direction);const auto& before=originals.at(std::string(direction)+"/"+std::string(roles[i]));expect(doc.clip.frames.size()==before.frames.size(),"Unedited direction frame count");for(std::size_t frame=0;frame<before.frames.size();++frame)pose(doc.clip.frames[frame],before.frames[frame],"Unedited direction remains intact");}}
    for(const auto& stage:sequence.stages){const auto doc=fc::loadConverterBaseEditor(base/"pack.json",stage.document.slot,"runRight");expect(doc.clip.frames.size()==stage.animation.clip.frames.size(),"Selected direction reloads correct role");for(std::size_t frame=0;frame<doc.clip.frames.size();++frame)pose(doc.clip.frames[frame],stage.animation.clip.frames[frame],"Selected source direction round trip");}
    sourceReload(base,folder);
    expect(read(input)==savedInput,"Source HKX remains unchanged");
    for(const auto cuts:{fc::ConverterWallRunCuts{0,2},{2,1},{1,4},{1,1.00001f},{std::numeric_limits<float>::quiet_NaN(),2}}){fc::ConverterWallRunSequence invalid;expect(!fc::authorWallRunSequence(source,edits,"runUp",cuts,invalid,failure)&&invalid.stages.empty(),"Invalid boundary is rejected atomically");}
    fc::ConverterWallRunSequence invalidDirection;expect(!fc::authorWallRunSequence(source,edits,"hang",{1,2},invalidDirection,failure),"Non-wall-running direction is rejected");
    rejects([&]{fc::sliceConverterTimeline(whole.clip,{{"frameRange",{-1,10}}});},"Negative frame range rejected");rejects([&]{fc::sliceConverterTimeline(whole.clip,{{"frameRange",{1,1}}});},"Empty frame range rejected");rejects([&]{fc::sliceConverterTimeline(whole.clip,{{"frameRange",{0,999999}}});},"Oversized frame range rejected");rejects([&]{fc::sliceConverterTimeline(whole.clip,{{"frameRange",{0,2}},{"rootShift",{0,std::numeric_limits<float>::infinity(),0}}});},"Nonfinite shift rejected");
    for(const auto& snapshot:source.snapshots)if(snapshot.path!=source.input)write(snapshot.path,snapshot.bytes);
    auto changed=read(input);changed.back()^=1;write(input,changed);rejects([&]{fc::exportConverterEditorGroup(exportStages,folder/"stale.zip");},"Changed source prevents atomic publication");expect(!std::filesystem::exists(folder/"stale.zip"),"Stale export writes no archive");
    std::cout<<checks<<" complete-action checks passed\n";return 0;
}
}
int main(int argc,char** argv){try{if(argc!=3)throw std::runtime_error("Expected pack.json and output directory");return run(argv[1],argv[2]);}catch(const std::exception& failure){std::cerr<<failure.what()<<'\n';return 1;}}
