function(fc_test name target source motion)
  if(motion AND NOT EXISTS "${FREECLIMB_MOTION_FILE}")
    return()
  endif()
  add_executable(${target} ${source})
  target_include_directories(${target} PRIVATE src)
  target_link_libraries(${target} PRIVATE FreeClimbAnimationInput FreeClimbSettings)
  if(MSVC)
    target_compile_options(${target} PRIVATE /utf-8)
  endif()
  if(motion)
    add_test(NAME ${name} COMMAND ${target} "${FREECLIMB_MOTION_FILE}")
  else()
    add_test(NAME ${name} COMMAND ${target})
  endif()
endfunction()

fc_test(pose_world_bone FreeClimbPoseWorldBoneTests tests/PoseWorldBoneTests.cpp TRUE)
fc_test(pose_rig FreeClimbPoseRigTests tests/PoseRigTests.cpp TRUE)
fc_test(animation_skeleton_binding FreeClimbAnimationSkeletonBindingTests tests/AnimationSkeletonBindingTests.cpp FALSE)
fc_test(overhang_search_performance FreeClimbOverhangSearchPerformanceTests tests/OverhangSearchPerformanceTests.cpp FALSE)
fc_test(ray_candidate_cache FreeClimbRayCandidateCacheTests tests/RayCandidateCacheTests.cpp FALSE)
fc_test(ray_collector_validation_cache FreeClimbRayCollectorValidationCacheTests tests/RayCollectorValidationCacheTests.cpp FALSE)
fc_test(search_retry FreeClimbSearchRetryTests tests/SearchRetryTests.cpp FALSE)
fc_test(obstacle_search_performance FreeClimbObstacleSearchPerformanceTests tests/ObstacleSearchPerformanceTests.cpp FALSE)
fc_test(binding_capture FreeClimbBindingCaptureTests tests/BindingCaptureTests.cpp FALSE)
fc_test(gamepad_input FreeClimbGamepadInputTests tests/GamepadInputTests.cpp FALSE)
fc_test(input_bindings FreeClimbInputBindingsTests tests/InputBindingsTests.cpp FALSE)
fc_test(user_settings FreeClimbUserSettingsTests tests/UserSettingsTests.cpp FALSE)
fc_test(translation_catalog FreeClimbTranslationCatalogTests tests/TranslationCatalogTests.cpp FALSE)
fc_test(stamina_mode FreeClimbStaminaModeTests tests/StaminaModeTests.cpp FALSE)
fc_test(animation_pack FreeClimbAnimationPackTests tests/AnimationPackTests.cpp TRUE)

fc_test(runtime_policy FreeClimbRuntimePolicyTests tests/RuntimePolicyTests.cpp FALSE)
fc_test(hkx_animation FreeClimbHkxAnimationTests tests/HkxAnimationTests.cpp FALSE)
fc_test(hkx_spline FreeClimbHkxSplineTests tests/HkxSplineTests.cpp FALSE)
target_link_libraries(FreeClimbHkxAnimationTests PRIVATE FreeClimbAnimationInput)
target_link_libraries(FreeClimbHkxSplineTests PRIVATE FreeClimbAnimationInput)
if(EXISTS "${FREECLIMB_LEGACY_MOTION_FILE}" AND EXISTS "${FREECLIMB_HKX_DIRECTORY}/hang.hkx")
  add_executable(FreeClimbAnimationOverrideTests tests/AnimationOverrideTests.cpp)
  target_link_libraries(FreeClimbAnimationOverrideTests PRIVATE FreeClimbAnimationInput)
  if(MSVC)
    target_compile_options(FreeClimbAnimationOverrideTests PRIVATE /utf-8)
  endif()
  add_test(NAME hkx_overrides COMMAND FreeClimbAnimationOverrideTests "${FREECLIMB_LEGACY_MOTION_FILE}" "${FREECLIMB_HKX_DIRECTORY}")
endif()

fc_test(finger_clearance FreeClimbFingerClearanceTests tests/FingerClearanceTests.cpp TRUE)
if(EXISTS "${FREECLIMB_LEGACY_MOTION_FILE}")
  add_executable(FreeClimbFingerCalibrationTests tests/FingerCalibrationTests.cpp)
  target_link_libraries(FreeClimbFingerCalibrationTests PRIVATE FreeClimbAnimationInput)
  if(MSVC)
    target_compile_options(FreeClimbFingerCalibrationTests PRIVATE /utf-8)
  endif()
  add_test(NAME legacy_finger_calibration COMMAND FreeClimbFingerCalibrationTests "${FREECLIMB_LEGACY_MOTION_FILE}")
  if(EXISTS "${FREECLIMB_MOTION_FILE}")
    add_test(NAME animation_pack_migration COMMAND FreeClimbAnimationPackTests "${FREECLIMB_LEGACY_MOTION_FILE}" "${FREECLIMB_MOTION_FILE}")
  endif()
endif()
fc_test(no_independent_hang FreeClimbNoIndependentHangTests tests/NoIndependentHangTests.cpp TRUE)
fc_test(falling_hang_entry FreeClimbFallingHangEntryTests tests/FallingHangEntryTests.cpp TRUE)
fc_test(selective_automatic_actions FreeClimbSelectiveAutomaticActionsTests tests/SelectiveAutomaticActionsTests.cpp TRUE)
fc_test(grounded_entry_exclusion FreeClimbGroundedEntryExclusionTests tests/GroundedEntryExclusionTests.cpp FALSE)
fc_test(grounded_entry_exclusion_review FreeClimbGroundedEntryExclusionReviewTests tests/GroundedEntryExclusionReviewTests.cpp FALSE)
fc_test(low_face_entry FreeClimbLowFaceEntryTests tests/LowFaceEntryTests.cpp FALSE)
fc_test(entry_footprint FreeClimbEntryFootprintTests tests/EntryFootprintTests.cpp FALSE)
fc_test(ground_support_entry FreeClimbGroundSupportEntryTests tests/GroundSupportEntryTests.cpp FALSE)
fc_test(ground_entry_geometry FreeClimbGroundEntryGeometryTests tests/GroundEntryGeometryTests.cpp FALSE)
fc_test(long_stair_entry FreeClimbLongStairEntryTests tests/LongStairEntryTests.cpp FALSE)
fc_test(attach_plane_coherence FreeClimbAttachPlaneCoherenceTests tests/AttachPlaneCoherenceTests.cpp FALSE)
fc_test(supported_idle FreeClimbSupportedIdleTests tests/SupportedIdleTests.cpp TRUE)
fc_test(entry_handoff FreeClimbEntryHandoffTests tests/EntryHandoffTests.cpp FALSE)
fc_test(inclined_top_probe FreeClimbInclinedTopProbeTests tests/InclinedTopProbeTests.cpp FALSE)
fc_test(top_exit_continuity FreeClimbTopExitContinuityTests tests/TopExitContinuityTests.cpp TRUE)
fc_test(automatic_variety_diagonal FreeClimbAutomaticVariety711Tests tests/AutomaticVariety711.cpp TRUE)
fc_test(diagonal_variety_safety FreeClimbDiagonalVarietySafetyTests tests/DiagonalVarietySafetyTests.cpp TRUE)
fc_test(fluidity_pose FreeClimbFluidityPoseTests tests/FluidityPoseTests.cpp TRUE)
fc_test(automatic_variety FreeClimbAutomaticVarietyTests tests/AutomaticVarietyTests.cpp TRUE)
fc_test(surface_action_pose FreeClimbSurfaceActionPoseTests tests/SurfaceActionPoseTests.cpp TRUE)
fc_test(pose_surface_distance FreeClimbPoseSurfaceDistanceTests tests/PoseSurfaceDistanceTests.cpp TRUE)
fc_test(ground_entry FreeClimbGroundEntryTests tests/GroundEntryTests.cpp TRUE)
fc_test(random_cadence FreeClimbRandomCadenceTests tests/RandomCadenceTests.cpp TRUE)
fc_test(controller_gravity FreeClimbControllerGravityTests tests/ControllerGravityTests.cpp FALSE)
fc_test(ground_motion_probe FreeClimbGroundMotionProbeTests tests/GroundMotionProbeTests.cpp FALSE)
fc_test(support_lifetime FreeClimbSupportLifetimeTests tests/SupportLifetimeTests.cpp FALSE)
fc_test(native_walkable_approach FreeClimbNativeWalkableApproachTests tests/NativeWalkableApproachTests.cpp FALSE)
fc_test(wall_run_obstacle FreeClimbWallRunObstacleTests tests/WallRunObstacleTests.cpp FALSE)
fc_test(wall_run_obstacle_pose FreeClimbWallRunObstaclePoseTests tests/WallRunObstaclePoseTests.cpp TRUE)
fc_test(climb_entry FreeClimbClimbEntryTests tests/ClimbEntryTests.cpp TRUE)
fc_test(random_actions FreeClimbRandomActionsTests tests/RandomActionsTests.cpp TRUE)
fc_test(traversal_audio_runtime FreeClimbTraversalAudioRuntimeTests tests/TraversalAudioRuntimeTests.cpp FALSE)
fc_test(diagonal_speed FreeClimbDiagonalSpeedTests tests/DiagonalSpeedTests.cpp TRUE)
fc_test(traversal_audio FreeClimbTraversalAudioTests tests/TraversalAudioTests.cpp TRUE)
fc_test(irregular_corner FreeClimbIrregularCornerTests tests/IrregularCornerTests.cpp TRUE)
fc_test(faceted_corner_safety FreeClimbFacetedCornerSafetyTests tests/FacetedCornerSafetyTests.cpp TRUE)
fc_test(new_motion_activation FreeClimbNewMotionActivationTests tests/NewMotionActivationTests.cpp TRUE)
fc_test(threepeat_motion FreeClimbThreepeatMotionTests tests/ThreepeatMotionTests.cpp TRUE)
fc_test(eave_bypass FreeClimbEaveBypassTests tests/EaveBypassTests.cpp TRUE)
fc_test(adaptive_obstacle FreeClimbAdaptiveObstacleTests tests/AdaptiveObstacleTests.cpp FALSE)
fc_test(obstacle_mantle FreeClimbObstacleMantleTests tests/ObstacleMantleTests.cpp TRUE)
fc_test(direct_mantle_pose FreeClimbDirectMantlePoseTests tests/DirectMantlePoseTests.cpp TRUE)
fc_test(mantle_selection FreeClimbMantleSelectionTests tests/MantleSelectionTests.cpp TRUE)
fc_test(corner_traversal FreeClimbCornerTraversalTests tests/CornerTraversalTests.cpp FALSE)
fc_test(slope_corner_continuation FreeClimbSlopeCornerContinuationTests tests/SlopeCornerContinuationTests.cpp FALSE)
fc_test(corner_integration FreeClimbCornerIntegrationTests tests/CornerIntegrationTests.cpp TRUE)
fc_test(edge_acquisition FreeClimbEdgeAcquisitionTests tests/EdgeAcquisitionTests.cpp TRUE)
fc_test(grip_edge FreeClimbGripEdgeTests tests/GripEdgeTests.cpp TRUE)
fc_test(retired_motions FreeClimbRetiredMotionTests tests/RetiredMotionTests.cpp TRUE)
fc_test(context_actions FreeClimbContextActionTests tests/ContextActionTests.cpp TRUE)
fc_test(roof_crest FreeClimbRoofCrestTests tests/RoofCrestTests.cpp FALSE)
fc_test(roof_crest_pose FreeClimbRoofCrestPoseTests tests/RoofCrestPoseTests.cpp TRUE)
fc_test(roof_transfer FreeClimbRoofTransferTests tests/RoofTransferTests.cpp FALSE)
fc_test(thin_wall_summit FreeClimbThinWallSummitTests tests/ThinWallSummitTests.cpp FALSE)
fc_test(margin_recovery FreeClimbMarginRecoveryTests tests/MarginRecoveryTests.cpp FALSE)
fc_test(ray_filter FreeClimbRayFilterTests tests/RayFilterTests.cpp FALSE)
fc_test(facet_grip FreeClimbFacetGripTests tests/FacetGripTests.cpp FALSE)
fc_test(distance_grab FreeClimbDistanceGrabTests tests/DistanceGrabTests.cpp FALSE)
fc_test(stepped_summit FreeClimbSteppedSummitTests tests/SteppedSummitTests.cpp FALSE)
fc_test(top_candidate_search FreeClimbTopCandidateSearchTests tests/TopCandidateSearchTests.cpp FALSE)
fc_test(top_candidate_pose FreeClimbTopCandidatePoseTests tests/TopCandidatePoseTests.cpp TRUE)
fc_test(traversal_capture FreeClimbTraversalCaptureTests tests/TraversalCaptureTests.cpp FALSE)
fc_test(attach_surface FreeClimbAttachSurfaceTests tests/AttachSurfaceTests.cpp FALSE)
fc_test(grab_input FreeClimbGrabInputTests tests/GrabInputTests.cpp FALSE)
fc_test(in_place_detach FreeClimbInPlaceDetachTests tests/InPlaceDetachTests.cpp TRUE)
fc_test(traversal_geometry FreeClimbGeometryTests tests/TraversalGeometryTests.cpp FALSE)
fc_test(back_flip_pose FreeClimbBackFlipPoseTests tests/BackFlipPoseTests.cpp TRUE)
fc_test(exit_continuity FreeClimbExitContinuityTests tests/ExitContinuityTests.cpp TRUE)
fc_test(stop_arm FreeClimbStopArmTests tests/StopArmTests.cpp TRUE)
fc_test(view_heading FreeClimbViewHeadingTests tests/ViewHeadingTests.cpp FALSE)
fc_test(skin_audit_budget FreeClimbSkinAuditBudgetTests tests/SkinAuditBudgetTests.cpp FALSE)
fc_test(late_world_update FreeClimbLateWorldUpdateTests tests/LateWorldUpdateTests.cpp FALSE)
fc_test(scene_propagation FreeClimbScenePropagationTests tests/ScenePropagationTests.cpp FALSE)
fc_test(pose_continuation FreeClimbContinuationTests tests/ContinuationTests.cpp FALSE)
fc_test(yaw_frame FreeClimbYawFrameTests tests/YawFrameTests.cpp FALSE)
fc_test(side_run_pose FreeClimbSideRunPoseTests tests/SideRunPoseTests.cpp TRUE)
fc_test(parkour FreeClimbParkourTests tests/ParkourTests.cpp TRUE)
fc_test(stability FreeClimbStabilityTests tests/StabilityTests.cpp TRUE)
fc_test(pose_health FreeClimbPoseHealthTests tests/PoseHealthTests.cpp FALSE)
fc_test(traversal FreeClimbTests tests/CoreTests.cpp FALSE)
fc_test(pose FreeClimbPoseTests tests/PoseTests.cpp TRUE)
fc_test(actions FreeClimbActionTests tests/ActionTests.cpp TRUE)
fc_test(scene_binding FreeClimbSceneBindingTests tests/SceneBindingTests.cpp TRUE)

foreach(target IN ITEMS FreeClimbStopArmTests FreeClimbSurfaceActionPoseTests FreeClimbSideRunPoseTests FreeClimbTopExitContinuityTests)
  if(TARGET ${target})
    target_link_libraries(${target} PRIVATE FreeClimbAnimationInput)
    if(EXISTS "${FREECLIMB_HKX_DIRECTORY}/hang.hkx")
      add_test(NAME ${target}_hkx COMMAND ${target} "${FREECLIMB_MOTION_FILE}" "${FREECLIMB_HKX_DIRECTORY}")
    endif()
  endif()
endforeach()

if(FREECLIMB_LOCAL_TESTS)
  if(NOT EXISTS "${CMAKE_SOURCE_DIR}/cmake/LocalTests.cmake")
    message(FATAL_ERROR "Local game inspection checks are not part of the portable source package")
  endif()
  include(cmake/LocalTests.cmake)
endif()


if(TARGET FreeClimbMigrateAnimationPack AND EXISTS "${FREECLIMB_MOTION_FILE}")
  find_package(Python3 COMPONENTS Interpreter QUIET)
  if(Python3_Interpreter_FOUND)
    add_test(NAME animation_pack_migration_tool COMMAND "${Python3_EXECUTABLE}" -X utf8
      "${CMAKE_SOURCE_DIR}/tests/MigrationToolTests.py" --tool $<TARGET_FILE:FreeClimbMigrateAnimationPack>
      --pack "${FREECLIMB_MOTION_FILE}" --work "${CMAKE_BINARY_DIR}/migration-tests")
  endif()
endif()

fc_test(universal_mantle_pose FreeClimbUniversalMantlePoseTests tests/UniversalMantlePoseTests.cpp TRUE)

fc_test(recessed_wall_transfer FreeClimbRecessedWallTransferTests tests/RecessedWallTransferTests.cpp FALSE)
